---
- name: House Keeping old log files
  hosts: devops
  vars:
    directories: ['E:\test-space-cleanup']
    #filepattern: ['r*']
    age: 3d

  tasks:
    - name: Find Log LogFiles
      tags: always
      ansible.windows.win_find:
        paths: "{{ directories }}"
        age: "{{ age }}"
        age_stamp: mtime
        patterns: [ '*1' ]
        recurse: yes
      register: filestoremove

    - name: list of files to be removed
      tags: always
      vars:
        files: "{{ filestoremove.files | json_query('[].path') }}"
      debug: var=files
      when: filestoremove.matched > 0

    - name: remove the files found - this would work only when you call the --tags=delete
      tags: never,delete
      vars:
        files: "{{ filestoremove.files | json_query('[].path') }}"
      win_file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ files }}"
      when: filestoremove.matched > 0
