---
- hosts: devops
  become: false
  tasks:

  - name: Run basic PowerShell script
    ansible.windows.win_shell: |
      $limit =  (Get-Date).AddDays(-25)
      $path = "E:\TFSBuildAgents\BET.Staging\_work"
      Get-ChildItem $path | ? { $_ -clike 'r*' } | Where-Object {($_.LastWriteTime -lt $limit) } | remove-item -force -recurse
